# Generated by Django 4.0.4 on 2022-05-24 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapmodel',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
