# Generated by Django 4.0.4 on 2022-05-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_main', '0002_alter_mapmodel_options_mapmodel_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodel',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
